### ISSUE TITLE
Ecto integration?

### ISSUE THREAD

**Issue by erlandsona** [keathley/norm#7]
Co-Worker Chris Miller (think y'all talked at lambda-squared Knoxville) shared you're talk on Norm after I gave a lunch and learn about utilizing opaque-types with dialyzer + [typed_ecto_schema](https://hexdocs.pm/typed_ecto_schema/TypedEctoSchema.html) to create some better guarantees about our code at compile-time.

I love your motivations for this library but I'd want the DSL to work well with our existing models/types without having to introduce a new DSL.

Do you have any plans to integrate with Ecto?

**Comment by keathley** [comment]
Hey @erlandsona. I don't have plans to build anything into Norm directly to support Ecto. I could see a higher-level library that provides support for this. But I'm not even sure what functionality you'd be wanting from something like that. Can you explain your use case a bit more?

**Comment by erlandsona** [comment]
Not having to repeat schemas already defined in an ecto schema for a norm spec... Similar to how [typed_ecto_schema](https://hexdocs.pm/typed_ecto_schema/TypedEctoSchema.html) took [typed_struct](https://github.com/ejpcmac/typed_struct) and made it work around ecto schema's. 
Granted, Dialyzer is a dumpster fire of uselessness but it serves it's purposes when it does find random issues 🤷‍♂
But it'd be nice if we could do this norm stuff against our existing ecto schemas.

FWIW: I've been doing Haskell/Elm in my free time for the past few years so I really appreciated all your awareness of existing type systems. Being able to do stuff that you'd otherwise need dependent types for is pretty freakin' cool. I've been bitten by that in Haskell & Elm, trying to reflect a runtime value back into a type. It's just not a thing.

**Comment by keathley** [comment]
I think it would be possible to take a Norm spec and convert it to an ecto schema. But I think there might be some issues because Norm allows you to say more things than an Ecto Schema can say, at least as far as I'm aware. I suppose you could also generate changeset functions which would allow for more expressiveness. But it seems like that might get confusing.

You could also just give up some of Norm's expressive power in the schema definition. But it seems like you might lose a lot of information if you do that.

So I'm not sure there is a clean way to do this with Norm atm. At least not without sacrificing a lot of what makes Norm powerful.

**Comment by joeyrosztoczy** [comment]
Just to randomly chime in on the discussion (I think Norm used at high levels - i.e. database or json/http api levels - is an interesting goal / roadmap, because that's where it can be applied to inter-service contracts that aren't dependent on inter-beam services or binary_to_term communication)

A couple thoughts:

(1) If the goal is _already defined ecto schemas_, and Norm is more expressive, then I'd guess schema translation would be doable (even if that takes place in like a norm_ecto style library, and required more feature support from norm itself).

(2) Changeset's are interesting, because they seem to be related to this idea of contract based design but not 1 to 1. You take proposed input to the DB and "validate that", but you also respond to response from some state in a downstream service (like the DB with a constraint) and propagate that to the calling service, which seems like it goes beyond the scope of Norm? Responding to a data state like in a constraint failure + feedback to the changeset, is also something not really solve-able by programming analysis whether static or dynamic, and better handled in integration tests. You'd still need those integration tests even if you had a Norm-specced callback to handle an Ecto constraint error response.

@erlandsona curious if the use case would be more for helping infer parts of a spec in functions that use an Ecto struct between them, so that (2) is mostly irrelevant, and features for (1) are needed instead?

_Disclaimer: not involved with the project just saw Chris's talk and was really inspired, want to learn as much as possible._

**Comment by erlandsona** [comment]
@joeyrosztoczy when I think of Design by Contract, I think [Make Impossible States Impossible](https://www.youtube.com/watch?v=IcgmSRJHu_8). Norm gives us an Elixir version of this idea (sort of). 

Elixir has [`@opaque`](https://hexdocs.pm/elixir/typespecs.html#user-defined-types) built in and lib's like [`typed_struct`](https://github.com/ejpcmac/typed_struct) to make working with them nicer and [`typed_ecto_schema`](https://hexdocs.pm/typed_ecto_schema/TypedEctoSchema.html)  integrates these ideas with Ecto.

But what I'm really longing for, is for Dialyzer to enable us to validate all branches of a Sum type are covered by a case / pattern match. **But** with 'success typing' Dialyzer is happy to just skip so long as only one branch will succeed. <- this makes it impossible to guarantee at compile time that our branching covers all possible states of the input. See that [I need to patch dialyzer](https://github.com/jeremyjh/dialyxir/issues/355#issuecomment-525935121) for this behavior :/

This is important to know at compile time so that you can start moving away from "primitive obsession" (Modeling switches in your domain as bool flags) and start composing smarter domain specific primitives that can encode some of the business logic at the construction/instantiation site which effectively pushes cyclomatic complexity to the edges of you program and eliminates it too.

**Comment by erlandsona** [comment]
As far as your question is concerned @joeyrosztoczy more directly. I think yes?

From what I've done with typed_ecto_schema so far, the two things I'm missing are better integration of typed_embedded_schema's using custom types with ecto types. <- What I was expecting to happen was to be able to define a sum type, use that as annotation of a field and have dialyzer validate any calling code can't call functions using that schema passing in data that isn't one of the branches of the sum.
And if dialyzer can't do that and improving dialyzer is too much work, then to at least have those validations at runtime. 
Which Norm does! But now I have two schema dsl's.
I like you're idea of a `norm_ecto` lib. 
The piece I'm missing from typed_ecto_schema is integration of custom types which honestly Norm rules would probably mitigate the need for...

**Comment by erlandsona** [comment]
Rather maybe this will provide a nice alternative in the future once they figure out exaustiveness checking...
[Gradualizer](https://github.com/josefs/Gradualizer)

**Comment by kieraneglin** [comment]
For those who got here by google, we added a basic helper that lets us use Norm with out changesets:

```elixir
  def validate_schema(changeset, schema) do
    %{changes: changes} = changeset
    fields_to_validate = Map.keys(changes)

    case conform(changes, selection(schema, fields_to_validate)) do
      {:ok, _} -> changeset
      {:error, errors} -> format_errors(changeset, errors)
    end
  end

  defp format_errors(changeset, errors) do
    formatted_errors =
      Enum.map(errors, fn %{path: [path], spec: spec} ->
        {path, {"failed schema validation", [validation: spec]}}
      end)

    %{changeset | errors: formatted_errors ++ changeset.errors, valid?: false}
  end
```

This might not fit every case but it working so far for us and it prevents us from duplicating validation logic.
